server:
   port: 11001
   servlet:
      contextPath: /sso
      
spring:
   datasource:
      url: jdbc:oracle:thin:@localhost:1521:sso
      database: sso
      user: sso
      password: sso
      driver-class-name: oracle.jdbc.driver.OracleDriver
   liquibase:
      changeLog: classpath:config/liquibase/db-changelog.xml
      url: jdbc:oracle:thin:@localhost:1521:sso
      user: sso
      password: sso
   jpa:
      database-platform: org.hibernate.dialect.Oracle12cDialect
      properties:
         hibernate:
            temp:
               use_jdbc_metadata_defaults: false
      hibernate:
         ddl-auto: none
   hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      
application:
   flavor: spring-security
   version: 0.0.1