server:
   port: 8082
   servlet:
      contextPath: /sso
      
spring:
   datasource:
      url: jdbc:h2:~/db/sso.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      database: sso
      user: SA
      password:
      driver-class-name: org.h2.Driver
   liquibase:
      changeLog: classpath:config/liquibase/db-changelog.xml
      url: jdbc:h2:~/db/sso.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      user: SA
      password:
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
         hibernate:
            temp:
               use_jdbc_metadata_defaults: false
      hibernate:
         ddl-auto: none
   hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      
application:
   flavor: spring-security
   version: 0.0.1